spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name: cards
#  datasource:
#    url: jdbc:h2:mem:cardsdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update

build:
  version: "4.0"

cards:
  message: "Cards Service - DEV"
  contactDetails:
    name: "Riverbank"
    email: "riverbank@example.com"
  onCallSupport:
    - (123) 456-7890
    - (987) 654-3210