server:
  port: 8090

spring:
  application:
    name: cards
  config:
    import:
      - "application_dev.yml"
      - "application_qa.yml"
      - "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "dev"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

build:
  version: "1.0"