server:
  port: 8080

spring:
  application:
    name: accounts
#  datasource:
#    url: jdbc:h2:mem:accountsdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
  sql:
    init:
      mode: always
  config:
    import:
      - "application_dev.yml"
      - "application_qa.yml"
      - "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "dev"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: refresh
#POST: http://localhost:8080/actuator/refresh

build:
  version: "1.0"

